version = 0.1

[default.deploy.parameters]
stack_name = "Zip2Confluence"
resolve_s3 = true
s3_prefix = "Zip2Confluence"
region = "us-east-1"
confirm_changeset = true
capabilities = ["CAPABILITY_IAM","CAPABILITY_NAMED_IAM"]
image_repositories = []
